In [9]:
import pandas as pd
import numpy as np
import os 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import time

In [17]:
fake_news_data = os.path.join(os.getcwd(), "notebooks", "Fake.csv")
true_news_data = os.path.join(os.getcwd(), "notebooks", "True.csv")

df_fake = pd.read_csv(fake_news_data)
df_true = pd.read_csv(true_news_data)

In [20]:
print("fake news data shape: ", df_fake.shape)
print("true news data shape: ", df_true.shape)

fake news data shape:  (23481, 4)
true news data shape:  (21417, 4)

In [22]:
print("fake news columns: ", df_fake.columns.tolist())
print("true news columns: ", df_true.columns.tolist())

fake news columns:  ['title', 'text', 'subject', 'date']
true news columns:  ['title', 'text', 'subject', 'date']

In [24]:
df_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [25]:
df_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [26]:
df_fake.isna().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [27]:
df_true.isna().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [31]:
df_fake.info()
print("--------------------------------")
print("--------------------------------")
df_true.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB
--------------------------------
--------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    21417 non-null  object
 1   text     21417 non-null  object
 2   subject  21417 non-null  object
 3   date     21417 non-null  object
dtypes: object(4)
memory usage: 669.4+ KB

In [35]:
# fig, axes = plt.subplots(1, 2, figsize=(18, 6))
# sns.histplot(df_fake['date'], bins=30, kde=True, ax=axes[0])
# axes[0].set_title('Histogram of Fake News Date')

# not working yet, will fix later